### PR TITLE
Assure that variable size is int

### LINKED ISSUE #10: Issues with Python 2 on WIN64 due to variables with long shape entries
In Python 2, Win64, numpy shapes are long. This is a quirk of the platform. On all other platforms the shape of an array has int entries.

This means that when one uses some shape information to generate a picos variable, the `size` parameter can easily be a long value or a tuple of long values.

Picos seems to accept this with no issues. However, when cvxopt is called, cvxopt fails because it expects indexes to be int, not long.

### PR DESCRIPTION
**Pull request by sergiocallegari**
Closes #10

### CODE REVIEW

**Comment by sergiocallegari** [comment]
If this is acceptable, once merged can you please make a release on Pypi? I would like to bump the minimal picos version required by my PyDSM project and assure that it works on all platforms

**Comment by gsagnol** [comment]
Thank you Sergio ! I try to make a release by Wednesday.

**Comment by gsagnol** [comment]
Hi Sergio !
Sorry, I had other urgent matters to deal with this week. But I promise I'll make a release before Monday!

**Comment by sergiocallegari** [comment]
On 28/08/2015 22:41, gsagnol wrote:

> Hi Sergio !
> Sorry, I had other urgent matters to deal with this week. But I promise I'll 
> make a release before Monday!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gsagnol/picos/pull/11#issuecomment-135883252.
> 
> Hi,

Thanks!!! In fact I am overwhelmed by work too!

Sergio

**Comment by gsagnol** [comment]
Done, the version 1.1.1 has been released and uploaded on Pypi.

**Pull request merged**
