### PR TITLE
Partial trace bug fixed

### PR DESCRIPTION
**Pull request by peterwittek**

### CODE REVIEW

**Comment by ziofil** [comment]
The partial_trace now works indeed, but when I concatenate two expressions obtained in this way I get the error `UnboundLocalError: local variable 'retmat' referenced before assignment` at line 1292 of `expression.py`.

**Comment by ziofil** [comment]
This reproduces the problem for me.

```
import picos as pic
import numpy as np
P = pic.Problem()
B = pic.new_param('B',np.identity(4))

pic.partial_trace(B)//pic.partial_trace(B)
```

**Comment by gsagnol** [comment]
This is, again, a conflict between `cvxopt` and `np.int64` types.
I solved one side of the problem but now at some point we have cvx sparse matrices created by
`cvx.spmatrix(V,I,J)`
where I or J may contain np.int64 numbers.  @peterwittek , do you have an idea to fix this globally, in an elegant way (I do not want to cast all np.int64 as int everywhere...)

**Comment by peterwittek** [comment]
This is external to PICOS. I opened a bug report on this (cvxopt/cvxopt#85). What we could do is prevent promotion to `np.int64`. There is already a bit of type juggling around this, mainly to be able to use `np.product`. For products, dummy for loops actually [work reasonably well](https://stackoverflow.com/questions/2104782/returning-the-product-of-a-list). In Python 3.6, iterating over lists or tuples, this function is about five times faster than `np.product`, and only 20% slower on `np.arrays`:

```python
import numpy as np

def prod(l):
    r = 1
    for x in l:
        r *= x
    return r

a = list(range(2, 20))
b = tuple(a)
c = np.array(a)

%timeit prod(a)
%timeit prod(b)
%timeit prod(c)
%timeit np.product(a)
%timeit np.product(b)
%timeit np.product(c)
```

**Comment by gsagnol** [comment]
Maybe a quick workaround would be to change all calls to `cvx.spmatrix` to a picos internal function
`picos.tools.spmatrix`, which catches errors due to `int64`s inside a `try` block ? I will try to do this this afternoon. Anyway, it's good you opend a bug report on cvxopt.

**Pull request merged**
