### PR TITLE
Extra parameter to allow importing an SDPA solution

### PR DESCRIPTION
**Pull request by peterwittek**
SDPA can run distributed on a cluster, but this execution is difficult to control from Python/Picos. It can make sense to write the SDPA file, solve it on the cluster, and read back the result (issue #39).

### CODE REVIEW

**Comment by IgnacioRubioScola** [comment]
Thank you for your time, but now I'm having this error when (solving directly with sdpa or cvxopt):

  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/ign/Documents/TESTSDPA/temp.py", line 62, in <module>
    prob_D.solve(verbose=0,solver='cvxopt')

  File "/usr/local/lib/python3.5/dist-packages/picos/problem.py", line 4807, in solve
    return self.solve(solve_via_dual=False)

  File "/usr/local/lib/python3.5/dist-packages/picos/problem.py", line 4897, in solve
    primals, duals, obj, sol = self._cvxopt_solve()

  File "/usr/local/lib/python3.5/dist-packages/picos/problem.py", line 4997, in _cvxopt_solve
    hard_coded_bounds=True)

  File "/usr/local/lib/python3.5/dist-packages/picos/problem.py", line 3144, in _make_cvxopt_instance
    self.cvxoptVars['A'] = spmatrix([], [], [], (0, ss), tc='d')

NameError: name 'spmatrix' is not defined

**Comment by peterwittek** [comment]
I can't reproduce it locally, but you can add this before line 3144 to make it work:
```python
from cvxopt import spmatrix
```

**Comment by IgnacioRubioScola** [comment]
Now the local solvers work again, but after solving externally with:
 "solution = prob_D.solve(solver='sdpa', sdpa_params={'read_solution': 'mysdpa.out'}):"
I have this error,
  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/ign/Dropbox/Privé/Python/testSDPA/TestSDPA.py", line 53, in <module>
    solution = prob_D.solve(solver='sdpa', sdpa_params={'read_solution': 'mysdpa.out'})

  File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/problem.py", line 4818, in solve
    sol = dual.solve()

  File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/problem.py", line 4924, in solve
    primals, duals, obj, sol = self._sdpa_solve()

  File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/problem.py", line 6773, in _sdpa_solve
    for Gsi in self.cvxoptVars['Gs']]

TypeError: 'NoneType' object is not iterable

**Comment by peterwittek** [comment]
Are you sure that the PICOS problem you defined corresponds to the solution you are trying to read in?

**Comment by IgnacioRubioScola** [comment]
Here is the example that I'm trying to solve:
https://ctrlv.it/python/18117/2961556763
then i do:
sdpa mysdpa.dat-s  mysdpa.out
and when i want to recover the data:
File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/problem.py", line 6773, in _sdpa_solve
for Gsi in self.cvxoptVars['Gs']]

**Comment by peterwittek** [comment]
I can confirm the problem. The current git of PICOS has all sorts of problems in `expression.py`, so I wait until those are fixed.

**Comment by gsagnol** [comment]
Hi ! 
@peterwittek can you precise what you mean by all sorts of problem? You state this in the current git version, does it mean that these problems are not in the latest release?

**Comment by peterwittek** [comment]
Some indentation problems in `expression.py` around line 804.

**Comment by gsagnol** [comment]
Hmmm, sorry, I accepted a merge request without checking that it was working... Hope the problem is fixed, now.

**Comment by peterwittek** [comment]
Yes, it works, thanks.

Regarding the problem of @ignrub, I checked what was going on. If you commented out the line that writes out the file, then you would get these errors. Writing the file triggers filling out the respective arrays. PR #41 takes care of it. Please try it.

**Comment by IgnacioRubioScola** [comment]
After reinstalling PICOS, I'm still having this error (with and without commenting out the line that writes out the file ):

 File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/problem.py", line 4923, in solve
    primals, duals, obj, sol = self._sdpa_solve()

  File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/problem.py", line 6798, in _sdpa_solve
    value = svecm1(cvx.matrix(value))  # value was the svec

  File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/tools.py", line 1375, in svecm1
    raise ValueError('vec should be of dimension n(n+1)/2')

ValueError: vec should be of dimension n(n+1)/2

**Comment by peterwittek** [comment]
I can't reproduce this error with the example you gave. It works fine here.

**Comment by IgnacioRubioScola** [comment]
Maybe I'm running a different version of sdpa (I have sdpa 7.3.9 from ubuntu xenial source) and the .out is perhaps different from yours, here is what I obtained after doing "sdpa mysdpa.dat-s mysdpa.out" from the .py above :
https://ctrlv.it/c/18131/3531001060
Can you tell me if this .out is similar to yours? 
Thank you in advance!

**Comment by peterwittek** [comment]
I copy-pasted your solution and works just as fine. I tried it with Python 3.6 on Arch Linux, and Anaconda 4.3 (also Python 3.6) on Ubuntu 16.04, SDPA 7.3.8 and also your output, and it works consistently.

**Comment by IgnacioRubioScola** [comment]
I have tested on three different machines with python 3.5.2 and 3.6.1rc1 and I have always the same error:
File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/tools.py", line 1375, in svecm1
raise ValueError('vec should be of dimension n(n+1)/2')
and
File "/home/ign/.pyenv/versions/3.6.1rc1/envs/general/lib/python3.6/site-packages/picos/tools.py", line 1375, in svecm1
raise ValueError('vec should be of dimension n(n+1)/2')

Please can you verify that, in your picos/tools.py, the function 'svecm1' is the same as the git gsagnol/picos (start at line 1369):
https://ctrlv.it/python/18153/2212117940

**Comment by peterwittek** [comment]
Yes, it is identical: I am using the latest git. The next possible source of error can be the version of cvxopt. Mine  is version 1.1.9.

**Comment by IgnacioRubioScola** [comment]
In Ubuntu 10.10 and 10.04 with python 3.6 with the last version of /gsagnol/picos (picos=1.1.3.dev0) with dependencies cvxopt=1.1.9, numpy=1.12.0 and six=1.10.0. When I run the example above (https://ctrlv.it/python/18117/2961556763 and  "sdpa mysdpa.dat-s mysdpa.out" ), I always get the same error "ValueError('vec should be of dimension n(n+1)/2')" (full error https://ctrlv.it/python/18408/1842655212). I really don't know what I'm doing wrong...

**Comment by peterwittek** [comment]
The mystery is getting deeper. I also tried it with Python 2.7.13, and it works just fine. I don't have any insight on what could possibly go wrong.

**Comment by IgnacioRubioScola** [comment]
Which BLAS and LAPACK library package are you compiling cvxopt with? I use ATLAS (libatlas-dev from Ubuntu repository)

**Comment by peterwittek** [comment]
On Arch, it is stock BLAS and LAPACK (version 3.7.0). On Ubuntu+Anaconda, I think it uses the MKL that ships with Anaconda (I use cvxopt in the conda-forge repo).

**Comment by IgnacioRubioScola** [comment]
I've tried the cvxopt from conda-forge and still the same error, I also tried with python2. Here another simple example, https://ctrlv.it/python/18569/1810227302, and gives a similar error on python2 and 3:
  File "/usr/local/lib/python3.5/dist-packages/PICOS-1.1.3.dev0-py3.5.egg/picos/problem.py", line 6800, in _sdpa_solve
TypeError: wrong matrix dimensions
I hope this will give information to identify the problem...

**Comment by peterwittek** [comment]
Got it. When you wrote out the file, it did not dualize it, but when you read it back, first it dualized the problem, and then tried to read in the solution. This worked:

```python
solution = prob.solve(solver='sdpa', solve_via_dual=False, sdpa_params={'read_solution': 'test2.out'})
```

**Comment by IgnacioRubioScola** [comment]
It works!!!! It works on python2, python3.5 and python3.6!!! Thank you very much!! 
Maybe it would be useful to modify your comment (adding "solve_via_dual=False") on issue #39 to clarify other users.

**Comment by peterwittek** [comment]
PR #43 skips the automatic dualization if the solution is read back manually. I think with this, we could close #39.

**Pull request merged**
